// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using report.persistence.Context;

#nullable disable

namespace report.persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230123155322_EditedInclude")]
    partial class EditedInclude
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("report.domain.Entities.ContactInfo", b =>
                {
                    b.Property<Guid>("UUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("InfoContent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("InfoType")
                        .HasColumnType("integer");

                    b.Property<string>("PersonID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("PersonsUUID")
                        .HasColumnType("uuid");

                    b.HasKey("UUID");

                    b.HasIndex("PersonsUUID");

                    b.ToTable("ContactInfo");
                });

            modelBuilder.Entity("report.domain.Entities.Persons", b =>
                {
                    b.Property<Guid>("UUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Firma")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UUID");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("report.domain.Entities.ContactInfo", b =>
                {
                    b.HasOne("report.domain.Entities.Persons", null)
                        .WithMany("ContactInfo")
                        .HasForeignKey("PersonsUUID");
                });

            modelBuilder.Entity("report.domain.Entities.Persons", b =>
                {
                    b.Navigation("ContactInfo");
                });
#pragma warning restore 612, 618
        }
    }
}
